[2025-09-11T18:34:36.042+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-11T18:34:36.156+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_etl.load manual__2025-09-11T18:34:25.987047+00:00 [queued]>
[2025-09-11T18:34:36.179+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_etl.load manual__2025-09-11T18:34:25.987047+00:00 [queued]>
[2025-09-11T18:34:36.180+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-09-11T18:34:36.212+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): load> on 2025-09-11 18:34:25.987047+00:00
[2025-09-11T18:34:36.240+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10083) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-11T18:34:36.236+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'currency_etl', 'load', 'manual__2025-09-11T18:34:25.987047+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/currency_etl.py', '--cfg-path', '/tmp/tmpy2g32tg1']
[2025-09-11T18:34:36.242+0000] {standard_task_runner.py:72} INFO - Started process 10084 to run task
[2025-09-11T18:34:36.243+0000] {standard_task_runner.py:105} INFO - Job 190: Subtask load
[2025-09-11T18:34:36.555+0000] {task_command.py:467} INFO - Running <TaskInstance: currency_etl.load manual__2025-09-11T18:34:25.987047+00:00 [running]> on host b37bbfb35b9c
[2025-09-11T18:34:37.024+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_etl' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-09-11T18:34:25.987047+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-11T18:34:25.987047+00:00'
[2025-09-11T18:34:37.026+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-11T18:34:37.056+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-11T18:34:37.059+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/load.py']
[2025-09-11T18:34:37.087+0000] {subprocess.py:86} INFO - Output:
[2025-09-11T18:34:40.061+0000] {subprocess.py:93} INFO - DB_URL = postgresql+psycopg2://***:***@postgres/***
[2025-09-11T18:34:40.081+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-09-11T18:34:40.082+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/load.py", line 51, in <module>
[2025-09-11T18:34:40.087+0000] {subprocess.py:93} INFO -     latest = latest_clean_file()
[2025-09-11T18:34:40.089+0000] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^
[2025-09-11T18:34:40.089+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/load.py", line 21, in latest_clean_file
[2025-09-11T18:34:40.092+0000] {subprocess.py:93} INFO -     files.sort(key=lambda f: datetime.strptime(f.stem.split("_")[1], "%Y-%m-%d"))
[2025-09-11T18:34:40.093+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/load.py", line 21, in <lambda>
[2025-09-11T18:34:40.098+0000] {subprocess.py:93} INFO -     files.sort(key=lambda f: datetime.strptime(f.stem.split("_")[1], "%Y-%m-%d"))
[2025-09-11T18:34:40.099+0000] {subprocess.py:93} INFO -                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-11T18:34:40.100+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
[2025-09-11T18:34:40.101+0000] {subprocess.py:93} INFO -     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
[2025-09-11T18:34:40.102+0000] {subprocess.py:93} INFO -                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-11T18:34:40.103+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime
[2025-09-11T18:34:40.104+0000] {subprocess.py:93} INFO -     raise ValueError("time data %r does not match format %r" %
[2025-09-11T18:34:40.105+0000] {subprocess.py:93} INFO - ValueError: time data '20250910' does not match format '%Y-%m-%d'
[2025-09-11T18:34:40.262+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-11T18:34:40.353+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-11T18:34:40.414+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=currency_etl, task_id=load, run_id=manual__2025-09-11T18:34:25.987047+00:00, execution_date=20250911T183425, start_date=20250911T183436, end_date=20250911T183440
[2025-09-11T18:34:40.489+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-11T18:34:40.491+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 190 for task load (Bash command failed. The command returned a non-zero exit code 1.; 10084)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-11T18:34:40.531+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-11T18:34:40.655+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-11T18:34:40.679+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
